### ISSUE TITLE
difference with loopback-ds-computed-mixin?

### ISSUE THREAD

**Issue by josx** [fullcube/loopback-ds-calculated-mixin#1]
Is there any difference with https://github.com/fullcube/loopback-ds-computed-mixin/ ?

**Comment by mrfelton** [comment]
@josx The difference is that calculated properties are calculated and stored with the object when a model instance is first created. Computed properties are dynamically computed every time a model instance is loaded.

**Comment by josx** [comment]
@mrfelton Thanks for explanation!
